
export const INTRO_MUSIC_OPEN = true;
export const GAMEPLAY_MUSIC_OPEN = true;
export const PLAYER_FIRE_INTERVAL = 300;
const ENEMY_TANK_TYPE1_FIRE_INTERVAL = 4000;
export default ENEMY_TANK_TYPE1_FIRE_INTERVAL;
export const ENEMY_TANK_TYPE2_FIRE_INTERVAL = 2500;
