
const INTRO_MUSIC_OPEN = true;
const GAMEPLAY_MUSIC_OPEN = true;
const PLAYER_FIRE_INTERVAL = 300;
const ENEMY_TANK_TYPE1_FIRE_INTERVAL = 4000;
const ENEMY_TANK_TYPE2_FIRE_INTERVAL = 2500;

export { INTRO_MUSIC_OPEN, GAMEPLAY_MUSIC_OPEN, PLAYER_FIRE_INTERVAL, ENEMY_TANK_TYPE1_FIRE_INTERVAL, ENEMY_TANK_TYPE2_FIRE_INTERVAL }
